create sequence roles_seq start with 1 increment by 50;
create sequence usuarios_seq start with 1 increment by 50;
create table roles (id bigint not null, nome varchar(20) unique, primary key (id));
create table usuarios (id bigint not null, password varchar(50), user_name varchar(50) unique, primary key (id));
create table usuarios_roles (role_id bigint not null, usuario_id bigint not null, unique (usuario_id, role_id));
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
create sequence roles_seq start with 1 increment by 50;
create sequence usuarios_seq start with 1 increment by 50;
create table roles (id bigint not null, nome varchar(20) unique, primary key (id));
create table usuarios (id bigint not null, password varchar(50), user_name varchar(50) unique, primary key (id));
create table usuarios_roles (role_id bigint not null, usuario_id bigint not null, unique (usuario_id, role_id));
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
create sequence roles_seq start with 1 increment by 50;
create sequence usuarios_seq start with 1 increment by 50;
create table roles (id bigint not null, nome varchar(20) unique, primary key (id));
create table usuarios (id bigint not null, password varchar(50), user_name varchar(50) unique, primary key (id));
create table usuarios_roles (role_id bigint not null, usuario_id bigint not null, unique (usuario_id, role_id));
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
create sequence roles_seq start with 1 increment by 50;
create sequence usuarios_seq start with 1 increment by 50;
create table roles (id bigint not null, nome varchar(20) unique, primary key (id));
create table usuarios (id bigint not null, password varchar(50), user_name varchar(50) unique, primary key (id));
create table usuarios_roles (role_id bigint not null, usuario_id bigint not null, unique (usuario_id, role_id));
alter table if exists usuarios_roles add constraint FKihom0uklpkfpffipxpoyf7b74 foreign key (role_id) references roles;
alter table if exists usuarios_roles add constraint FKqcxu02bqipxpr7cjyj9dmhwec foreign key (usuario_id) references usuarios;
